/** Declaration file generated by dts-gen */

declare module "file-extension" {
    function fileExtension(filename: string): string;
    function fileExtension(filename: string, opts?: { preserveCase: boolean }): string;
}



